name: Daily EMY Automation

on:
  schedule:
    - cron: '0 6 * * *' # Τρέχει κάθε μέρα στις 08:00 ώρα Ελλάδος
  workflow_dispatch: # Σου επιτρέπει να το τρέχεις χειροκίνητα

jobs:
  run-logic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Tools
      run: pip install -r requirements.txt
    - name: Execute Script
      run: python screenshot.py
    - name: Save Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-update: Screenshot & Excel" || echo "No changes"
        git push
